apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 342375422541.dkr.ecr.us-east-1.amazonaws.com/daniel_chatbot:chatbot-latest
          ports:
            - containerPort: 8080
