apiVersion: v1
kind: Pod
metadata:
  name: chatbot
spec:
  containers:
  - name: chat-container
    image: 342375422541.dkr.ecr.us-east-1.amazonaws.com/daniel_chatbot:latest
    ports:
    - containerPort: 8080

